name: gnn-pred-stab
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - ipython
  - ipywidgets
  - jupyter_client
  - jupyter_core
  - jupyterlab_pygments
  - jupyterlab_widgets
  - matplotlib=3.5.0
  - networkx=2.6.3
  - numpy=1.21.2
  - pandas=1.3.5
  - pillow=8.4.0
  - pip=21.2.4
  - pyg=2.0.3=py39_torch_1.10.0_cu113
  - pytest=6.2.5
  - python=3.9.7
  - pytorch=1.10.2=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch-lightning=1.5.9
  # - scikit-learn=1.0.2
  - seaborn=0.11.2
  - tqdm=4.62.3
  - yaml=0.2.5
  - pyarrow
  - pip:
    - hydra-core==1.1.1
    - ogb==1.3.2

prefix: